### PR TITLE
Laravel 5.5 Support

### PR DESCRIPTION
**Pull request by gtapps**
Hello,

This pull request includes support for laravel 5.5.

Cheers,
Gabriel

### CODE REVIEW

**Comment by gtapps** [comment]
BTW once you also merge the pull requests on "sofa/hookable" you can edit this current composer.json to not point to my hookable package that also required a few tweaks to support laravel 5.5.

**Comment by itsjavi** [comment]
maybe you should rebase on top of master and push it again.
tests are failing

**Comment by ragingdave** [comment]
@gtapps Are you planning on moving forward with this PR or not?

**Comment by gtapps** [comment]
Hello guys,
This pull request has a few broken things, there are even more changes required to work with laravel 5.5 after testing it a lot more. So this is not a good base to start with after testing it.

**Pull request closed without merging**
