### PR TITLE
upgrade to laravel 5.4

### PR DESCRIPTION
**Pull request by Remo**
@jarektkaczyk  this minus the readme and composer.json changes seems to work okay so far

### CODE REVIEW

**Comment by ebbbang** [comment]
@Remo do you know why this failed ?

I looked and it is throwing error on phpcs psr2 test ...
Can you fix it ?

I couldn't find the migration file it threw the error on ...

Or guide me in way so i can fix it ...

**Comment by Remo** [comment]
@ebbbang It's because the migration file doesn't have a namespace, here's the PR, only have to test it https://github.com/ortic/eloquence/pull/6

**Comment by Remo** [comment]
@ebbbang migration works for me,  I'm not entirely sure if we should load the migrations in the service provider. I personally do it for almost all my libraries, but some people like to specify the path manually.

**Comment by Remo** [comment]
@diego-vieira there's another problem with your migration file. I've pulled `ortic/eloquence` into a project of mine where I'm using sqlite in my test cases. There the index can't be created because of this:
```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such function: meta_value (SQL: create index meta_attributes_index_value on meta_attributes (meta_key, meta_value(20)))
```

Shall we just skip that index on sqlite?

**Comment by diego-vieira** [comment]
@Remo sorry for the delay, indeed, it seems that the index is only covering MySQL.

**Comment by ebbbang** [comment]
Hey @Remo, @diego-vieira, @jarektkaczyk can any of you please fix the code coverage so we can get along with this merge ?

**Comment by jarektkaczyk** [comment]
upgraded to 5.4 https://github.com/jarektkaczyk/eloquence/tree/5.4

threre's one issues with pagination and `searchable` since now laravel strips `select` bindings when running *countForPagination*.

**Pull request closed without merging**
