### PR TITLE
Add support Laravel 6

### PR DESCRIPTION
**Pull request by mewebstudio**
Related requests:
https://github.com/jarektkaczyk/hookable/pull/24
https://github.com/jarektkaczyk/eloquence-metable/pull/1
https://github.com/jarektkaczyk/eloquence-mutable/pull/4
https://github.com/jarektkaczyk/eloquence-validable/pull/3
https://github.com/jarektkaczyk/eloquence-base/pull/17

### CODE REVIEW

**Comment by hafael** [comment]
👍

**Comment by alirezamaleky** [comment]
thank you

**Comment by jarektkaczyk** [comment]
thanks @mewebstudio tagged v6

**Comment by mewebstudio** [comment]
> thanks @mewebstudio tagged v6

You're welcome @jarektkaczyk

**Pull request merged**
