### PR TITLE
Add Formattable Trait

### PR DESCRIPTION
**Pull request by RomainLanz**
Hey @jarektkaczyk!

:construction: **We have collision problems with our method `setAttribute`. How can we handle that?**

With that we can easily format our attributes.

````php
class User
{
    use Formattable;

    protected $formats = [
        'first_name' => ['strtolower', 'ucwords],
        'last_name' => 'strtolower|ucwords',
        'phone' => 'formatPhone',
        'slug' => '\Str@slug',
    ];

    public function formatPhone($phone)
    {
        return "({$phone})";
    }
}

$user->first_name = 'roMAin'; // Will set 'Romain'
$user->last_name = 'laNZ'; // Will set 'Lanz'
$user->phone = 555; // Will set '(555)'
$user->slug = 'Awesome package!'; // Will set 'awesome-package'
````

I also change the readme to be better and to document `Formattable`.

### CODE REVIEW

**Comment by RomainLanz** [comment]
Why not create an organisation and put all of these add-on on their own repository?

Btw, we can create à package nammed hookable to register hook into Eloquent. With that we wouldn't have any problems with some collisions.

**Comment by jarektkaczyk** [comment]
Hey, exactly that's the problem we have to solve. I thought about macros, but that's also tricky. I will think about it.

**Comment by RomainLanz** [comment]
Maybe ask to Taylor to add some hook into Eloquent.

**Comment by RomainLanz** [comment]
I didn't see any way to do that except to create a package like `eloquent-hook` to hook Eloquent process.

**Comment by RomainLanz** [comment]
Any news about this?

Maybe my code need some refactoring.

**Comment by jarektkaczyk** [comment]
Hey Romain, I've been out and busy now, so haven't got the chance to work on it so far. Mergin this one and I will think about the solution later.

**Comment by jarektkaczyk** [comment]
Oh and btw I'm **against** validation on the model ;)

**Comment by RomainLanz** [comment]
@jarektkaczyk Hey, no problem, I'm just writing that to have some stuff on the roadmap :p

**Pull request merged**
